// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beta.proto

#ifndef PROTOBUF_beta_2eproto__INCLUDED
#define PROTOBUF_beta_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Beta {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_beta_2eproto();
void protobuf_AssignDesc_beta_2eproto();
void protobuf_ShutdownFile_beta_2eproto();

class Parameters;

// ===================================================================

class Parameters : public ::google::protobuf::Message {
 public:
  Parameters();
  virtual ~Parameters();

  Parameters(const Parameters& from);

  inline Parameters& operator=(const Parameters& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Parameters& default_instance();

  void Swap(Parameters* other);

  // implements Message ----------------------------------------------

  Parameters* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Parameters& from);
  void MergeFrom(const Parameters& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 L = 1 [default = 1];
  inline bool has_l() const;
  inline void clear_l();
  static const int kLFieldNumber = 1;
  inline ::google::protobuf::int32 l() const;
  inline void set_l(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Beta.Parameters)
 private:
  inline void set_has_l();
  inline void clear_has_l();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 l_;
  friend void  protobuf_AddDesc_beta_2eproto();
  friend void protobuf_AssignDesc_beta_2eproto();
  friend void protobuf_ShutdownFile_beta_2eproto();

  void InitAsDefaultInstance();
  static Parameters* default_instance_;
};
// ===================================================================


// ===================================================================

// Parameters

// required int32 L = 1 [default = 1];
inline bool Parameters::has_l() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Parameters::set_has_l() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Parameters::clear_has_l() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Parameters::clear_l() {
  l_ = 1;
  clear_has_l();
}
inline ::google::protobuf::int32 Parameters::l() const {
  // @@protoc_insertion_point(field_get:Beta.Parameters.L)
  return l_;
}
inline void Parameters::set_l(::google::protobuf::int32 value) {
  set_has_l();
  l_ = value;
  // @@protoc_insertion_point(field_set:Beta.Parameters.L)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Beta

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_beta_2eproto__INCLUDED
